### ISSUE TITLE
Logging just to ask some questions

### ISSUE THREAD

**Issue by mohsinulhaq** [Andarist/use-onclickoutside#2]
1. https://github.com/Andarist/use-onclickoutside/blob/master/src/index.ts#L38
when is the above line helpful?
2. https://github.com/Andarist/use-onclickoutside/blob/master/src/index.ts#L69
why is there a `!` before handler?
Thanks.

**Comment by Andarist** [comment]
1. [This great post](https://overreacted.io/making-setinterval-declarative-with-react-hooks/) explains this technique. It's used to create a single cached listener (in 2nd effect) which can always access the newest prop (by accessing it on mutable ref). Otherwise you would end up with things cached in the closure.

2. This just casts to a boolean, could be just `[handler]` and it would work just fine.

**Comment by mohsinulhaq** [comment]
Alright, thanks a lot! :) Closing this issue.
