### ISSUE TITLE
How this package works so it uses event listeners effectively?

### ISSUE THREAD

**Issue by RIP21** [Andarist/use-onclickoutside#5]
I was using different package for the same purpose, but he appeared to be buggy. Simple fix to the issue referenced below is to remove `[]` from the `useEffect` so it actually attaches and re-attaches event listeners on every rerender which is far from effective.
https://github.com/sandiiarov/use-events/issues/35

I then used this package and it works flawlessly, but I'm, by looking at the source code, not sure how it makes this event listeners problem any better. Can you please explain here the trick that you may use to fix this issue?
I see some magical usage of `ref` which I know can be used not only for refs in hooks world, but for some other stuff (as sort of the bucket of the values), but I still can't get it. 
Will greatly appreciate if you will explain it in detail, please :)

**Comment by Andarist** [comment]
I create unique listener - not reusing the one passed in as argument. The one passed in as arguments gets "cached" in `handlerRef` - this allows my listener to reach for the most fresh one each time, otherwise it would reach for "stale" `handler`.

I also trigger adding/removing of my unique listener based on truthiness of the `handler` argument:
https://github.com/Andarist/use-onclickoutside/blob/33fbf7deecc46140b8d6be05c42f41c5a6d10ac4/src/index.ts#L69

This post explains this (first bit about using ref) quite nicely - https://overreacted.io/making-setinterval-declarative-with-react-hooks/

**Comment by RIP21** [comment]
Thanks. TIL! :)
